### PR TITLE
SSL certs

### LINKED ISSUE #36: Failure in SSL verification requires hack
In packed-mn, we had to make this hack:
https://github.com/metanorma/packed-mn/blob/c1904865ca7e5375ecb4acbf2e5e86fe682ebb9f/bin/metanorma#L178-L186

```ruby
Net::HTTP.class_eval do
  alias _use_ssl= use_ssl=

  def use_ssl= boolean
    self.ca_file = cert_file_path
    self.verify_mode = OpenSSL::SSL::VERIFY_PEER
    self._use_ssl = boolean
  end
end
```

And supply our own CA file (from cURL which uses Mozilla's: https://curl.se/ca/cacert.pem).

This should not be necessary given that we already have this patch:
https://github.com/metanorma/ruby-packer/blob/master/.patches/ruby/0004-ssl-certs.patch

Without this hack, we get these errors:

https://github.com/metanorma/packed-mn/runs/4454422319?check_suite_focus=true
```
2021-12-08T08:12:37.7764700Z Downloading font "source" from https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip
2021-12-08T08:12:37.8281670Z Invalid URL: https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip. Error: #<Down::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>.
2021-12-08T08:12:37.8318500Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/fontist-1.13.0/lib/fontist/font_installer.rb:68:in `download_file': Invalid URL: https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip. Error: #<Down::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>. (Fontist::Errors::InvalidResourceError)
2021-12-08T08:12:37.8321240Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/fontist-1.13.0/lib/fontist/font_installer.rb:41:in `extract'
```

https://github.com/metanorma/packed-mn/runs/4454422376?check_suite_focus=true
```
2021-12-08T08:11:57.6276950Z #<Thread:0x00007ff4bf7a0650@/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
2021-12-08T08:11:57.6285680Z /__ruby_packer_memfs__/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
2021-12-08T08:11:57.6288470Z 	from /__ruby_packer_memfs__/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
2021-12-08T08:11:57.6290150Z 	from /__ruby_packer_memfs__/lib/ruby/2.6.0/net/http.rb:996:in `connect'
2021-12-08T08:11:57.6291650Z 	from /__ruby_packer_memfs__/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
2021-12-08T08:11:57.6292890Z 	from /__ruby_packer_memfs__/lib/ruby/2.6.0/net/http.rb:919:in `start'
2021-12-08T08:11:57.6293980Z 	from /__ruby_packer_memfs__/lib/ruby/2.6.0/net/http.rb:605:in `start'
2021-12-08T08:11:57.6295140Z 	from /__ruby_packer_memfs__/lib/ruby/2.6.0/net/http.rb:481:in `get_response'
2021-12-08T08:11:57.6296600Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-ietf-1.9.2/lib/relaton_ietf/scrapper.rb:125:in `get_page'
2021-12-08T08:11:57.6298430Z 	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-ietf-1.9.2/lib/relaton_ietf/scrapper.rb:111:in `rfc_item'
```

### PR DESCRIPTION
**Pull request by alexeymorozov**
Closes #36 

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
There is an issue with the Linux build because Ubuntu 16.04 is no longer available.

**Comment by ronaldtse** [comment]
@alexeymorozov macos-packed-mn is also failing. I see that it's supposed to pass?

**Comment by alexeymorozov** [comment]
@ronaldtse Sorry. Made changes, seems it works, will merge when CI is finished.

**Review by ronaldtse — APPROVED** [review]
Thank you @alexeymorozov !

**Comment by ronaldtse** [comment]
All passed and merging. @alexeymorozov can you help updated packed-mn to remove the SSL hack? Thanks!

**Comment by ronaldtse** [comment]
And a new release here please with a change log message in the CHANGELOG file that the CA SSL file is now included as per the new version.

**Pull request merged**
